fbwfmgr /enable
fbwfmgr /addvolume C:
fbwfmgr /addvolume D:
fbwfmgr /addexclusion c: "\Users"
fbwfmgr /addexclusion c: "\Windows\Installer"
fbwfmgr /addexclusion c: "\Program Files\TortoiseGit"
fbwfmgr /addexclusion c: "\Program Files\Adobe"
fbwfmgr /addexclusion c: "\Program Files\Common Files\Adobe"
fbwfmgr /addexclusion c: "\Program Files\Microsoft"
fbwfmgr /addexclusion c: "\Program Files\Nutstore"
fbwfmgr /addexclusion c: "\Program Files\Dassault Systemes"
fbwfmgr /addexclusion c: "\ProgramData\DassaultSystemes"
fbwfmgr /addexclusion c: "\Program Files\Git"
fbwfmgr /addexclusion c: "\Program Files\Symantec"
fbwfmgr /addexclusion c: "\ProgramData\Symantec"
fbwfmgr /addexclusion c: "\ProgramData\SymEFASI"
fbwfmgr /addexclusion c: "\Program Files\Common Files\Symantec Shared"
fbwfmgr /addexclusion c:"\Windows\System32\drivers\BazisPortableCDBus.sys"
fbwfmgr /addexclusion c:"\Windows\System32\drivers\TweakCubeVD.sys"
fbwfmgr /addexclusion c: "\windows\bootstat.dat"
fbwfmgr /addexclusion D: "\Documents"
fbwfmgr /addexclusion D: "\WIN_VHD\"
fbwfmgr /addexclusion D: "\PortableApps"
fbwfmgr /addexclusion D: "\Program Files"



